### ISSUE TITLE
[feature req] tokenization of other languages

### ISSUE THREAD

**Issue by azah** [andylokandy/simsearch-rs#5]
simsearch-rs totally fails on Korean text. How involved would it be to have it tokenize hangeul?

searching `던지(요)` should match id 866 (name: `-던지(요)`, but gives a top result of id 1527 (name: `에게로 【너에게로 다가간다】)`.

[raw json](https://gist.githubusercontent.com/azah/1cd9b2401e087c2c2a374bcf1a550ac8/raw/46f5ee8772ff8027674e5f7ad3f32e5cefc99d8b/output.json)
```rust
use std::{error::Error, fs};

use serde::{Deserialize, Serialize};
use simsearch::SimSearch;

#[derive(Debug, Deserialize, Serialize)]
struct Entry {
    id: i64,
    name: String,
    typical_example: String,
    translation: String,
    category_eng: String,
    category_kor: String,
}

fn main() -> Result<(), Box<dyn Error + 'static>> {
    let mut engine: SimSearch<i64> = SimSearch::new();

    let data = fs::read_to_string("./output.json")?;
    let entries: Vec<Entry> = serde_json::from_str(&data)?;

    for entry in &entries {
        engine.insert(entry.id, &entry.name);
    }

    let results = engine.search("던지(요)");
    let top_match = results[1];

    let entry = entries.iter().filter(|e| e.id == top_match).collect::<Vec<_>>();

    Ok(())
}
```

**Comment by andylokandy** [comment]
It seems to be caused by the levenshtein calculate algrithom from `strsim`, so I'd make a seperate test on it later.

**Comment by andylokandy** [comment]
Solved by https://github.com/andylokandy/simsearch-rs/commit/3b44b214977e8259aa15a07d9e5749e3ea233458
